<?php
# This file was automatically generated by the MediaWiki 1.43.9
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/MainConfigSchema.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
        exit;
}




## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "Ima";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "";

## The protocol and server name to use in fully-qualified URLs
$wgServer = "https://ima.wiki.net.ar";

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL paths to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogos = [
        '1x' => "$wgResourceBasePath/resources/assets/logo-ima.jpg",
        'icon' => "$wgResourceBasePath/resources/assets/logo-ima.jpg",
];

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgPasswordSender = "admin@ima.wiki.net.ar";
$wgEmergencyContact = "admin@ima.wiki.net.ar";

# 3. Configuración del Servidor SMTP Externo
$wgSMTP = [
    'host'      => 'smtp.email.us-phoenix-1.oci.oraclecloud.com', # Servidor SMTP (Usa 'ssl://' para puerto 465 o 'tls://' para puerto 587)
    'IDHost'    => 'ima.wiki.net.ar',       # El dominio de tu Wiki
    'port'      => 587,                    # Puerto del servidor SMTP (465 o 587)
    'auth'      => true,                   # Requiere autenticación
    'username'  => 'ocid1.user.oc1..aaaaaaaazbigozi7glmolue7v4sc7rhhnogekbs7lwmj2yh4nujjggexhmoq@ocid1.tenancy.oc1..aaaaaaaatr6pgacm4n67qjo6fqr3fd7fypkj5iym3kspn74ej5n246cfkvva.pj.com',# Tu usuario/correo de inicio de sesión
    'password'  => '>8veM7}1O#7o3dqgwAe6' # Tu contraseña de aplicación (NO la personal, usa un token)
];

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "mysql";
$wgDBserver = "db";
$wgDBname = "mediawiki";
$wgDBuser = "mediawiki";
$wgDBpassword = "8jVAhDhaIy6CCUXfF3BPEj3bc42WULHK";

# MySQL specific settings
$wgDBprefix = "";
$wgDBssl = false;

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Shared database table
# This has no effect unless $wgSharedDB is also set.
$wgSharedTables[] = "actor";

## Shared memory settings
$wgMainCacheType = CACHE_ACCEL;
$wgMemCachedServers = [];

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = true;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = true;

# Site language code, should be one of the list in ./includes/languages/data/Names.php
$wgLanguageCode = "es";

# Time zone
$wgLocaltimezone = "America/Argentina/Buenos_Aires";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publicly accessible from the web.
#$wgCacheDirectory = "$IP/cache";

$wgSecretKey = "ef84bb8243fe57799eb47d5a879d0d933fdc5d4b788d02ec8450d9057b896ef0";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "d4fd3ec690717790";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

# The following permissions were set based on your choice in the installer
$wgGroupPermissions["*"]["edit"] = false;

## Default skin: you can change the default skin. Use the internal symbolic
## names, e.g. 'vector' or 'monobook':
$wgDefaultSkin = "vector-2022";

# Enabled skins.
# The following skins were automatically enabled:
wfLoadSkin( 'MinervaNeue' );
wfLoadSkin( 'MonoBook' );
wfLoadSkin( 'Timeless' );
wfLoadSkin( 'Vector' );


# End of automatically generated settings.
# Add more configuration options below.

$wgVectorDefaultSkinVersionForPublicUsers = '2022';
$wgVectorDefaultSkinVersionForExistingAccounts = '2022';
$wgVectorDefaultSkinVersionForNewAccounts = '2022';

# Uso del editor visual
wfLoadExtension( 'VisualEditor' );
$wgVisualEditorDefaultUserOptions['visualeditor-editor'] = 'visualeditor';
$wgVisualEditorDefaultUserOptions['visualeditor-tabs'] = 'prefer-visual';
